package medicalApp.velociraptors.com;

import java.util.ArrayList;

import junit.framework.TestCase;

/**
 * The class <code>MedicalHistoryTest</code> contains tests for the class
 * {@link <code>MedicalHistory</code>}, specifically testing the addOrders method.
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 4/8/11 9:30 PM
 *
 * @author Danny Cook
 *
 * @version $Revision$
 */
public class MedicalHistoryTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public MedicalHistoryTest() {
		
	}
	
	/**
	 * Testing response for pulling data from a null appointment.
	 * 
	 */
	public void testNullAppointment() {
		TreatmentRecord t = new TreatmentRecord("bob", null, "orders");
		ArrayList<TreatmentRecord> al = new ArrayList<TreatmentRecord>();
		al.add(t);
		MedicalHistory mh = new MedicalHistory(al);
		System.out.println(mh.toString());
		
		assertEquals(mh.addOrders(t, "null"), "Addition Failed! Please check the parameters and try again.");
	}
	
	/**
	 * Testing response for adding DoctorOrders containing a null string.
	 *
	 * @param name the test name
	 */
	public void testNullDoctorOrders() {
		Appointment a = new Appointment("today", "bob", 1);
		TreatmentRecord t = new TreatmentRecord("bob", a, "orders");
		ArrayList<TreatmentRecord> al = new ArrayList<TreatmentRecord>();
		al.add(t);
		MedicalHistory mh = new MedicalHistory(al);
		System.out.println(mh.toString());
		
		assertEquals(mh.addOrders(t, "null"), "Addition Successful!");
	}
	
	/**
	 * Testing response for searching a histArray that is empty.
	 *
	 * @param name the test name
	 */
	public void testEmptyHistArray() {
		Appointment a = new Appointment("today", "bob", 1);
		MedicalHistory mh = new MedicalHistory();
		TreatmentRecord t = new TreatmentRecord("bob", a, "orders");
		
		assertEquals(mh.addOrders(t, "orders"), "Addition Failed! Please check the parameters and try again.");
	}
	
	/**
	 * Testing response for passing in a null treatment record.
	 */
	public void testNullTreatmentRecord() {
		Appointment a = new Appointment("today", "bob", 1);
		TreatmentRecord t = new TreatmentRecord("bob", a, "orders");
		ArrayList<TreatmentRecord> al = new ArrayList<TreatmentRecord>();
		al.add(t);
		MedicalHistory mh = new MedicalHistory(al);
		
		assertEquals(mh.addOrders(null, "orders"), "Addition Failed! Please check the parameters and try again.");
	}
	
	/**
	 * Testing response for passing in legitimate data for all parameters.
	 * 
	 * @param name
	 */
	public void testFullData() {
		Appointment a = new Appointment("today", "bob", 1);
		TreatmentRecord t = new TreatmentRecord("bob", a, "orders");
		ArrayList<TreatmentRecord> al = new ArrayList<TreatmentRecord>();
		al.add(t);
		MedicalHistory mh = new MedicalHistory(al);
		System.out.println(mh.toString());
		
		assertEquals(mh.addOrders(t, "orders"), "Addition Successful!");
	}
	

}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = medicalApp.velociraptors.com
 * package.sourceFolder = VelociraptorMedApp/src
 * superclassType = junit.framework.TestCase
 * testCase = MedicalHistoryTest
 * testClassType = MedicalHistory
 */